/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author diekl
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        decorateTableTarefas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListaVazia = new javax.swing.JPanel();
        jLabelListaVaziaIcon = new javax.swing.JLabel();
        jLabelListaVaziaSubTitulo = new javax.swing.JLabel();
        jLabelListaVaziaTitulo = new javax.swing.JLabel();
        jPanelTooBar = new javax.swing.JPanel();
        jLabelTooBarrTitle = new javax.swing.JLabel();
        jLabelTooBarSubTitle = new javax.swing.JLabel();
        jPanelProjeto = new javax.swing.JPanel();
        jLabelProjetosTitulo = new javax.swing.JLabel();
        jLabelProjetoAdd = new javax.swing.JLabel();
        jPanelTrefas = new javax.swing.JPanel();
        jLabelTarefasTitulo = new javax.swing.JLabel();
        jLabelTarefasAdd = new javax.swing.JLabel();
        jPanelProjetoLista = new javax.swing.JPanel();
        jScrollPaneProjeto = new javax.swing.JScrollPane();
        jListProjeto = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTarefas = new javax.swing.JTable();

        jPanelListaVazia.setBackground(java.awt.Color.white);

        jLabelListaVaziaIcon.setBackground(new java.awt.Color(0, 153, 153));
        jLabelListaVaziaIcon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelListaVaziaIcon.setForeground(new java.awt.Color(0, 153, 153));
        jLabelListaVaziaIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelListaVaziaIcon.setText("Nenhuma tarefa por aqui");

        jLabelListaVaziaSubTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelListaVaziaSubTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

        jLabelListaVaziaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelListaVaziaTitulo.setForeground(new java.awt.Color(153, 153, 153));
        jLabelListaVaziaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelListaVaziaTitulo.setText("clique no botão \"+\" para adicionar uma nova terefa");

        javax.swing.GroupLayout jPanelListaVaziaLayout = new javax.swing.GroupLayout(jPanelListaVazia);
        jPanelListaVazia.setLayout(jPanelListaVaziaLayout);
        jPanelListaVaziaLayout.setHorizontalGroup(
            jPanelListaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaVaziaLayout.createSequentialGroup()
                .addGroup(jPanelListaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelListaVaziaIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelListaVaziaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelListaVaziaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelListaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelListaVaziaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelListaVaziaSubTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelListaVaziaLayout.setVerticalGroup(
            jPanelListaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaVaziaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelListaVaziaIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelListaVaziaTitulo)
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(jPanelListaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelListaVaziaLayout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jLabelListaVaziaSubTitulo)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 800));

        jPanelTooBar.setBackground(new java.awt.Color(0, 153, 153));

        jLabelTooBarrTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTooBarrTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTooBarrTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N
        jLabelTooBarrTitle.setText(" Todo App");

        jLabelTooBarSubTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTooBarSubTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTooBarSubTitle.setText("Anote tudo, não esqueça de nada");

        javax.swing.GroupLayout jPanelTooBarLayout = new javax.swing.GroupLayout(jPanelTooBar);
        jPanelTooBar.setLayout(jPanelTooBarLayout);
        jPanelTooBarLayout.setHorizontalGroup(
            jPanelTooBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTooBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelTooBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTooBarrTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTooBarSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanelTooBarLayout.setVerticalGroup(
            jPanelTooBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTooBarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelTooBarrTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTooBarSubTitle)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanelProjeto.setBackground(java.awt.Color.white);
        jPanelProjeto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelProjetosTitulo.setBackground(new java.awt.Color(0, 153, 153));
        jLabelProjetosTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelProjetosTitulo.setForeground(new java.awt.Color(0, 153, 153));
        jLabelProjetosTitulo.setText("Projetos");

        jLabelProjetoAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jLabelProjetoAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProjetoAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelProjetoLayout = new javax.swing.GroupLayout(jPanelProjeto);
        jPanelProjeto.setLayout(jPanelProjetoLayout);
        jPanelProjetoLayout.setHorizontalGroup(
            jPanelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProjetosTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jLabelProjetoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelProjetoLayout.setVerticalGroup(
            jPanelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProjetoAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelProjetosTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelTrefas.setBackground(java.awt.Color.white);
        jPanelTrefas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTarefasTitulo.setBackground(new java.awt.Color(0, 153, 153));
        jLabelTarefasTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelTarefasTitulo.setForeground(new java.awt.Color(0, 153, 153));
        jLabelTarefasTitulo.setText("Tarefas");

        jLabelTarefasAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jLabelTarefasAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTarefasAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTrefasLayout = new javax.swing.GroupLayout(jPanelTrefas);
        jPanelTrefas.setLayout(jPanelTrefasLayout);
        jPanelTrefasLayout.setHorizontalGroup(
            jPanelTrefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrefasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTarefasTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTarefasAdd)
                .addContainerGap())
        );
        jPanelTrefasLayout.setVerticalGroup(
            jPanelTrefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrefasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTrefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTarefasTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTarefasAdd))
                .addContainerGap())
        );

        jPanelProjetoLista.setBackground(java.awt.Color.white);
        jPanelProjetoLista.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jListProjeto.setBackground(new java.awt.Color(255, 255, 255));
        jListProjeto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jListProjeto.setForeground(new java.awt.Color(0, 0, 0));
        jListProjeto.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListProjeto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListProjeto.setFixedCellHeight(50);
        jListProjeto.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPaneProjeto.setViewportView(jListProjeto);

        javax.swing.GroupLayout jPanelProjetoListaLayout = new javax.swing.GroupLayout(jPanelProjetoLista);
        jPanelProjetoLista.setLayout(jPanelProjetoListaLayout);
        jPanelProjetoListaLayout.setHorizontalGroup(
            jPanelProjetoListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProjetoListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneProjeto)
                .addContainerGap())
        );
        jPanelProjetoListaLayout.setVerticalGroup(
            jPanelProjetoListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjetoListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneProjeto)
                .addContainerGap())
        );

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableTarefas.setBackground(java.awt.Color.white);
        jTableTarefas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableTarefas.setForeground(new java.awt.Color(0, 153, 153));
        jTableTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTarefas.setGridColor(new java.awt.Color(255, 255, 255));
        jTableTarefas.setRowHeight(50);
        jTableTarefas.setSelectionBackground(new java.awt.Color(153, 255, 255));
        jTableTarefas.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTableTarefas);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTooBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelProjetoLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTrefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTooBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTrefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProjetoLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelProjetoAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProjetoAddMouseClicked
        // TODO add your handling code here:
        ProjetoDialogTela projetoDialogTela = new ProjetoDialogTela(this, rootPaneCheckingEnabled);
        projetoDialogTela.setVisible(true);
    }//GEN-LAST:event_jLabelProjetoAddMouseClicked

    private void jLabelTarefasAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTarefasAddMouseClicked
        // TODO add your handling code here:
        TarefaDialogTela tarefaDialogTela = new TarefaDialogTela(this, rootPaneCheckingEnabled);
        //tarefaDialogTela.setProjeto(null);
        tarefaDialogTela.setVisible(true);
    }//GEN-LAST:event_jLabelTarefasAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelListaVaziaIcon;
    private javax.swing.JLabel jLabelListaVaziaSubTitulo;
    private javax.swing.JLabel jLabelListaVaziaTitulo;
    private javax.swing.JLabel jLabelProjetoAdd;
    private javax.swing.JLabel jLabelProjetosTitulo;
    private javax.swing.JLabel jLabelTarefasAdd;
    private javax.swing.JLabel jLabelTarefasTitulo;
    private javax.swing.JLabel jLabelTooBarSubTitle;
    private javax.swing.JLabel jLabelTooBarrTitle;
    private javax.swing.JList<String> jListProjeto;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelListaVazia;
    private javax.swing.JPanel jPanelProjeto;
    private javax.swing.JPanel jPanelProjetoLista;
    private javax.swing.JPanel jPanelTooBar;
    private javax.swing.JPanel jPanelTrefas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneProjeto;
    private javax.swing.JTable jTableTarefas;
    // End of variables declaration//GEN-END:variables


    public void decorateTableTarefas(){
        // Custumizando o header ta table de Tarefas
        jTableTarefas.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        jTableTarefas.getTableHeader().setBackground(new Color(0,153,153));
        jTableTarefas.getTableHeader().setForeground(new Color(255,255,255));
        
        //Criando um sort automatico para as colunas da table
        jTableTarefas.setAutoCreateRowSorter(true);
    }

}
